version: '3.7'

services:
  openrem:
    container_name: openrem
    restart: unless-stopped
    image: openrem/openrem:develop
    command: gunicorn openremproject.wsgi:application --bind 0.0.0.0:8000 --timeout 300
    volumes:
      - media_volume:/home/app/openrem/mediafiles
      - static_volume:/home/app/openrem/staticfiles
      - migrations_volume:/home/app/openrem/remapp/migrations
      - imports_volume:/imports
      - logs_volume:/logs
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    container_name: openrem-db
    restart: unless-stopped
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - db_backup:/db_backup
    env_file:
      - ./.env.prod

  nginx:
    container_name: openrem-nginx
    restart: unless-stopped
    image: nginx:stable-alpine
    volumes:
      - media_volume:/home/app/openrem/mediafiles
      - static_volume:/home/app/openrem/staticfiles
# For SELinux (RedHat, Fedora etc), add :z to the end of next two lines
      - ./nginx-conf/conf.d:/etc/nginx/conf.d
      - ./nginx-conf/certs:/etc/ssl/private
    ports:
      - 80:80
    depends_on:
      - openrem

  orthanc_1:
    container_name: openrem-orthanc-1
    restart: unless-stopped
    image: openrem/orthanc
    volumes:
      - imports_volume:/imports
# For SELinux (RedHat, Fedora etc), add :z to the end of next line
      - ./orthanc:/etc/share/orthanc/scripts/
    ports:
# DICOM store port (first number)
      - 104:4242
# Othanc web interface
#      - 8042:8042
    environment:
      MANUFACTURERS_TO_IGNORE: "{}"
      MODEL_NAMES_TO_IGNORE: "{}"
      STATION_NAMES_TO_IGNORE: "{}"
      SOFTWARE_VERSIONS_TO_IGNORE: "{}"
      DEVICE_SERIAL_NUMBERS_TO_IGNORE: "{}"
      USE_TOSHIBA_CT_EXTRACTOR: "true"
      TOSHIBA_EXTRACTOR_SYSTEMS: |
        {{'Toshiba', 'Aquilion'}, {'GE Medical Systems', 'Discovery STE'},}
      USE_PHYSICS_FILTERING: "true"
      PHYSICS_TO_KEEP: "{'physics',}"

      ORTHANC_JSON: |
        {
          // DICOM Store configuration
          "DicomAet" : "OPENREM",
          // Optional Orthan Web Interface
          "Name" : "OpenREM Orthanc",
          "RemoteAccessAllowed" : false,
          "AuthenticationEnabled" : true,
          "RegisteredUsers" : {
            "orthancuser": "demo"
          },
          // OpenREM Lua Script
          "LuaScripts" : [
            "/etc/share/orthanc/scripts/openrem_orthanc_config_docker.lua"
          ]
        }

volumes:
  media_volume:
  static_volume:
  migrations_volume:
  imports_volume:
  logs_volume:
  postgres_data:
  db_backup:
